name: CI

on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: trigger single Job
        uses: appleboy/jenkins-action@master
        with:
         url: "http://192.168.2.130:8080/jenkins"
         user: "Bharath"
         token: ${{ secrets.TOKEN }}
         job: "Bharath"
