name: Job_Trigger

on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: "Trigger jenkins job"
        uses: GoldenspearLLC/build-jenkins-job@master
        with:
         jenkins-url: ${{ secrets.JENKINS_URL }}
         jenkins-token: ${{ secrets.JENKINS_TOKEN }}
         user: "jenkins"
         job-path: "/root/.jenkins/jobs/Bharath"
         
 #     - name: Trigger jenkins job
 #       uses: jabbukka/jenkins-trigger@main
 #       with:
 #        url: ${{ secrets.JENKINS_URL }}
 #        job_name: "Bharath"
 #        user_name: ${{ secrets.JENKINS_USER }}
 #        api_token: ${{ secrets.JENKINS_TOKEN }}
 #        wait: "true"
 #        timeout: "1000"
