name: CI

on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Trigger jenkins job
        uses: jabbukka/jenkins-trigger@main
        with:
         url: "http://192.168.2.130:8080/jenkins"
         user_name: "Bharath"
         api_token: ${{ secrets.JENKINS_TOKEN }}
         job_name: "Bharath"
